/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function callJsCallback(callback: (...args: any[]) => any): void
export declare function callJsCallbackWithArgs(callback: (...args: any[]) => any): void
export declare function callJsCallbackWithReturn(callback: (...args: any[]) => any): string
export declare function callThreadsafeFunction(callback: (...args: any[]) => any, resolve: (...args: any[]) => any, reject: (...args: any[]) => any): unknown
export declare function createPromise(): Promise<string>
